# https://medium.com/@basi/docker-compose-from-development-to-production-88000124a57c
# https://blog.couchbase.com/deploy-docker-compose-services-swarm/
# https://medium.com/our-developer-stories/full-automation-with-docker-cloud-e096addedfb1
# https://medium.com/@Empanado/simple-continuous-deployment-with-docker-compose-docker-machine-and-gitlab-ci-9047765322e1
# https://semaphoreci.com/blog/2017/09/13/continuous-integration-with-docker-compose.html
# https://codefresh.io/docker-tutorial/continuous-integration-docker-compose/
# https://stackoverflow.com/questions/42302632/docker-compose-continuous-deployment-setup


down:
	docker-compose -f docker-compose-ci.yml down


prepare:
	git clone https://github.com/vespa-engine/sample-apps.git

ci:	
	sudo docker-compose -f docker-compose-ci.yml up -d # -d # with/without -d??

cihosts: # can be autogenerated
	docker-compose -f docker-compose-ci.yml exec admin0 /bin/bash /vespascripts/create_hosts.sh
	docker-compose -f docker-compose-ci.yml exec stateless0 /bin/bash /vespascripts/create_hosts.sh
	docker-compose -f docker-compose-ci.yml exec stateless1 /bin/bash /vespascripts/create_hosts.sh
	docker-compose -f docker-compose-ci.yml exec content0 /bin/bash /vespascripts/create_hosts.sh
	docker-compose -f docker-compose-ci.yml exec content1 /bin/bash /vespascripts/create_hosts.sh

runci:	
	docker-compose -f docker-compose-ci.yml exec admin0 /bin/bash /vespascripts/run-ci.sh

runcij:	
	docker-compose -f docker-compose-ci.yml exec admin0 /bin/bash /vespascripts/run-ci.sh basic-search-java


shell:
	docker-compose -f docker-compose-ci.yml exec admin0 /bin/bash
